api-platform/create-client

README.md
Add link for Facebook's Create React App.
=> Feat: Update of the readme file

src/ReactCrudGenerator.js, templates/react/actions/foo/show.js, templates/react/components/foo/List.js, templates/react/components/foo/Show.js, templates/react/components/foo/index.js, templates/react/reducers/foo/index.js, templates/react/reducers/foo/show.js, templates/react/routes/foo.js
1. Show component created for every endpoint.
2. List component has icons for show & edit actions
=> Show component

templates/react/components/foo/Show.js
bug fix, forgot to import Redirect from react-router-dom
=> import Redirect

templates/react/components/foo/Show.js, templates/react/components/foo/Update.js
caused by new version of create-react-app
=> Unexpected use of 'confirm' no-restricted-globals 

templates/react/actions/foo/show.js, templates/react/components/foo/Show.js, templates/react/reducers/foo/show.js
Changes to actions and reducers - refactoring.
Fix Show component - displaying loading message that was missed before
=> Refactor and fix fo Show component.

package.json, src/ReactCrudGenerator.js, src/index.js, templates/react/components/foo/List.js, templates/react/components/foo/Show.js, templates/react/routes/foo.js, templates/react/utils/itemToLinks.js, yarn.lock
Showing links in List component to Show components of linked objects (example below)
If this functionality is worth of beeing in the generator, the rest components can be updated as well :)
=> List links

src/ReactCrudGenerator.js, templates/react/utils/helpers.js
prefixed API that was missed in previous PR
=> Fix list links

README.md, Troubleshooting.md
=> documentation

.gitignore, .travis.yml, README.md, Troubleshooting.md, package.json, src/ReactCrudGenerator.js, templates/react/actions/foo/list.js, templates/react/components/foo/List.js, templates/react/reducers/foo/list.js, templates/react/utils/helpers.js
working example
https://api-front.geomysiar.pl/books/
=> Pagination

package.json, src/generators.js, src/generators/TypescriptInterfaceGenerator.js, src/generators/TypescriptInterfaceGenerator.test.js, src/index.js, templates/typescript/interface.ts, yarn.lock
also bumps api-doc-parser and fix compat :P
=> Add typescript interface generator

.travis.yml, README.md, package.json, yarn.lock
| Doc PR        | api-platform/docs#271
=> Auto deploy with Travis. Fix names.

src/generators/ReactNativeCrudGenerator.js, templates/react/utils/helpers.js
=> React native

src/index.js
=> generator options help update

src/generators/VueCrudGenerator.js, src/generators/VueCrudGenerator.test.js, templates/vue/components/foo/List.vue, templates/vue/error/SubmissionError.js, templates/vue/store/modules/foo/list.js
=> Fix Vue.js generator

templates/react/utils/helpers.js
=> [react] Improve utils

templates/react-common/utils/fetch.js
Fix bugs introduced by last PR.
=> Fix the new fetch implementation

templates/react/utils/helpers.js
It has no visual impact but generate a cleaner/simpler HTML code. WDYT @mysiar?
=> [react] Replace span by div in link lists

templates/react/utils/helpers.js
=> Fix an import bug

src/generators/ReactGenerator.js, src/generators/ReactNativeGenerator.js, templates/react-common/utils/fetch.js, templates/react/components/foo/Create.js, templates/react/components/foo/Form.js, templates/react/components/foo/List.js, templates/react/components/foo/Show.js, templates/react/components/foo/Update.js, templates/react/utils/helpers.js
* Switch from Bootstrap 3 to 4
* Fix a bug in `fetch` (context wasn't injected)
* Add support for the new `is-valid` class
* Switch from Glyphicons to Font Awesome because Glyphicons have been remove from Bootstrap and now cause a license issue
=> [react] Bootstrap 4 support

templates/react/components/foo/List.js, templates/vue/components/foo/List.vue
=> Merge empty cells in list headers

README.md
=> Fix link to doc

src/generators/VueGenerator.js
| Fixed tickets | #64
| Doc PR        | api-platform/doc#1234
=> Remove brackets for module import

templates/vue/components/foo/Create.vue, templates/vue/components/foo/Form.vue, templates/vue/components/foo/List.vue, templates/vue/components/foo/Show.vue, templates/vue/components/foo/Update.vue, templates/vue/routes/foo.js, templates/vue/store/modules/foo/create.js, templates/vue/store/modules/foo/delete.js, templates/vue/store/modules/foo/index.js, templates/vue/store/modules/foo/list.js, templates/vue/store/modules/foo/mutation-types.js, templates/vue/store/modules/foo/show.js, templates/vue/store/modules/foo/update.js, templates/vue/utils/fetch.js
| Bug fix?      | no (but yes, if use vue-cli with eslint
I propose some small fixes to make the code generated for VueJs more consistent (in syntax) and compatible with esLint when use the view-cli installation.
This is my first contribution on a project, so do not hesitate to tell me if it is not suitable.
DavidA.
=> Improved consistency and compatibility with eslint

src/generators/ReactGenerator.js, src/generators/ReactNativeGenerator.js
=> Hint the default index.js path

templates/vue/components/foo/List.vue
=> Missing "!" on pagination last condition

src/generators/BaseGenerator.js, templates/_entrypoint.js, templates/react-common/utils/fetch.js, templates/react/utils/helpers.js, templates/vue/utils/fetch.js
=> Improve the generated code by using the URL object

src/index.js, templates/react-common/actions/foo/create.js, templates/react-common/actions/foo/list.js, templates/vue/store/modules/foo/create/actions.js, templates/vue/store/modules/foo/list/actions.js, templates/vue/utils/fetch.js, yarn.lock
=> fix fetch with api url suffix in vuejs

templates/react-common/actions/foo/list.js, yarn.lock
| New feature?  |no
Prevent a 400 error.
=> Don't subscribe to Mercure when the list is empty

templates/react/components/foo/Show.js
=> Fix relation link

templates/react-native/components/foo/List.js, templates/react-native/components/foo/Show.js
| Fixed tickets | #93 
List & Show components
=> React native: display the id

package.json
| Fixed tickets | #117
| Doc PR        | api-platform/doc#117
=> Fix Cannot find module 'lodash'

README.md
=> Updated the samples from #105

templates/react-common/utils/dataAccess.js, yarn.lock
* Add support for fields having several errors
* Throw a better error message when the server returns invalid JSON
=> [React] Improve fetch

README.md
| Tickets       | fixes #... 
| Doc PR        | api-platform/docs#...
Removed the licensed badge as it already showed by Github.
=> Remove Licence Badge from README.md

templates/quasar/common/components/ActionCell.vue, templates/quasar/common/components/ConfirmDelete.vue, templates/quasar/common/components/Toolbar.vue, templates/quasar/common/mixins/CreateMixin.js, templates/quasar/common/store/create/state.js, templates/quasar/common/store/delete/state.js, templates/quasar/common/store/list/actions.js, templates/quasar/common/store/list/state.js, templates/quasar/common/store/show/state.js, templates/quasar/common/store/update/actions.js, templates/quasar/common/store/update/state.js, templates/quasar/components/foo/Filter.vue, templates/quasar/components/foo/Form.vue, templates/quasar/store/modules/foo/create/actions.js, templates/quasar/store/modules/foo/create/mutations.js, templates/quasar/store/modules/foo/create/state.js, templates/quasar/store/modules/foo/delete/actions.js, templates/quasar/store/modules/foo/delete/mutations.js, templates/quasar/store/modules/foo/delete/state.js, templates/quasar/store/modules/foo/list/actions.js, templates/quasar/store/modules/foo/list/mutations.js, templates/quasar/store/modules/foo/list/state.js, templates/quasar/store/modules/foo/show/actions.js, templates/quasar/store/modules/foo/show/mutations.js, templates/quasar/store/modules/foo/show/state.js, templates/quasar/store/modules/foo/update/actions.js, templates/quasar/store/modules/foo/update/mutations.js, templates/quasar/store/modules/foo/update/state.js
Fix state issues and better naming.
Fix update error.
Allow overriding action when item created.
Always return fetch promise from action.
| Tickets       | no
| Doc PR        | no
=> Fixes in Quasar generator

src/generators/QuasarGenerator.js
Use `Array.includes()` to check for existence of an element.
=> feat(chore): minor code refactor

src/generators/VueBaseGenerator.js, src/generators/VuetifyGenerator.js, src/generators/VuetifyGenerator.test.js, templates/vue-common/mixins/ListMixin.js, templates/vue-common/mixins/ShowMixin.js, templates/vue-common/mixins/UpdateMixin.js, templates/vue-common/store/modules/crud.js, templates/vue-common/utils/fetch.js, templates/vuetify/components/Toolbar.vue, templates/vuetify/components/foo/Filter.vue, templates/vuetify/views/foo/List.vue, templates/vuetify/views/foo/Show.vue, templates/vuetify/views/foo/Update.vue
| Deprecations? |no
| Tickets       | #190 
| Doc PR        | https://github.com/api-platform/docs/pull/993
=> fix VuetifyGenerator

src/index.js
| New feature?  | yes 
| Tickets       | fixes #196  
npx @api-platform/client-generator -g vuetify --jwt BEARERTOKEN https//exampleapi src/
=> add jwt auth

templates/react/components/foo/List.js
| Deprecations? | yes
| Tickets       | fixes #201
| Doc PR        | api-platform/docs#...
This upgrade componentWillReceiveProps to componentDidUpdate
Tested on demo project : https://github.com/matyo91/uniflow-admin
=> fix(react): Upgrade componentWillReceiveProps #201

CONTRIBUTING.md
| Tickets       | fixes #... 
| Doc PR        | api-platform/docs#...
This add `yarn install` step when bootstrapping project
=> fix(contributing): Fix contribution documentation

src/generators/VuetifyGenerator.js
| New feature?  no
| Doc PR        | api-platform/docs#...
=> Fix modules/crud path

templates/vue/router/foo.js
See #194 
| Tickets       | fixes #194
=> Restore vue router

templates/vue-common/mixins/ListMixin.js
Use sortDesc when using vuetify
=> Fix sort when using vuetify

src/generators/NuxtGenerator.js, src/generators/NuxtGenerator.test.js, templates/nuxt/store/notifications.js
=> fix nuxt generator notification store module

src/generators/NuxtGenerator.js, src/generators/NuxtGenerator.test.js, src/generators/VuetifyGenerator.test.js, src/index.js
=> Nuxt generator fixes

src/generators/VuetifyGenerator.js
| Bug fix?      | yes 
| Tickets       | n/a 
=> Vuetify: fix console output of generator

templates/vue/components/foo/List.vue
| Tickets       | fixes #240 
| Doc PR        | no
Hi, there. This is my first PR to this project. I didn't find any functional tests, therefore I have tested this code by my hands only.
=> fix invalid link to child objects, fixes #240

templates/react/components/foo/Form.js
| Tickets       | fixes #243 
| License      | MIT
| Doc PR      | 
Fix the React client generator by adding the missing import Field from 'redux-form'
Many thanks to @metaclass-nl who helped me a lot.
=> Fix #243 by importing Field in Form.js in the React generator

templates/next/components/foo/List.tsx, templates/next/pages/foos/index.tsx
=> fix(next): fix display of 0 when the list is empty

templates/vue/utils/fetch.js
| Bug fix?      | yes 
| Tickets       | fixes #249 
| Doc PR        | none
Properly import the `SubmissionError` class in `fetch.js` which is exported as `default`.
=> Properly import SubmissionError

package.json, src/index.js, yarn.lock
| New feature?  | yes 
| Tickets       | n/a
| Doc PR        | todo
=> feat: use the Next.js generator by default

.travis.yml, package.json, src/generators/BaseGenerator.js, src/generators/NextGenerator.js, src/generators/TypescriptInterfaceGenerator.test.js, templates/next/components/common/ReferenceLinks.tsx, templates/next/components/foo/Form.tsx, templates/next/components/foo/List.tsx, templates/next/components/foo/Show.tsx, templates/next/error/SubmissionError.ts, templates/next/types/Collection.ts, templates/next/types/foo.ts, templates/next/utils/dataAccess.ts
| Tickets       | #prett
Always generate pretty-printed code using Prettier 🎉
This PR also fixes some bugs in the Next.js generator because another nice side effect of using Prettier is that the validity of the generated code is now always checked.
=> feat: format generated code using Prettier

src/generators/QuasarGenerator.js
=> Fix doc code

templates/vue/router/foo.js
| Branch?       | main 
| New feature?  | yes 
| Tickets       | none 
| Doc PR        | none 
Dynamically import Vue components in routes and use common Webpack chunk name.
See https://router.vuejs.org/guide/advanced/lazy-loading.html
And https://webpack.js.org/api/module-methods/#magic-comments
=> Dynamically import Vue components in routes

package.json, yarn.lock
| Tickets       | n/a
This patch prevents executing the tests two times (one time for sources and one time for the compiled version in `lib/`).
=> Don't run tests two times

.github/workflows/ci.yml, .github/workflows/npm.yml
| Deprecations? | yes/no
| Tickets       | Fix #275 
A step is missing in the GitHub Actions job.
=> ci: fix build

src/generators/NextGenerator.js, templates/next/pages/foos/index.tsx
- added Pagination.tsx and mercure.ts files in NextGenerator.js
- fixed var name in getServerSideProps in list page
=> fix: added pagination and mercure files in NextGenerator

src/generators/VueGenerator.js, templates/vue/components/foo/Form.vue, templates/vue/utils/fetch.js
| Tickets       | -
| Doc PR        | -
This fixes some issues with the vuejs template preventing it from working with a new `vue create` project:
- missing the `hydra.js` file in the generated sources
- missing import from `hydra.js`
- unused import in `Form.vue`
=> fix: some things preventing the vue.js template from running as is

jest.config.js, templates/react/components/Field.tsx
=> fix: React generator

templates/next/components/common/Pagination.tsx, templates/next/components/common/ReferenceLinks.tsx, templates/next/components/foo/Form.tsx, templates/next/components/foo/List.tsx, templates/next/components/foo/Show.tsx
=> feat: add support for Next 13
