.travis.yml, package.json, src/index.js
| Doc PR        | todo
Add support for two new environment variables to configure the API entrypoint and the output directory: `API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT` and `API_PLATFORM_CLIENT_GENERATOR_OUTPUT`.
This is necessary for the new API Platform distribution I'm working on.
=> Add new environment variables

src/generators.js, src/generators/ReactCrudGenerator.js, src/generators/ReactCrudGenerator.test.js, src/generators/TypescriptInterfaceGenerator.js, src/generators/TypescriptInterfaceGenerator.test.js, src/index.js
| Fixed tickets | #30 
ping @alOneh
=> Allow custom template directory fix #30

src/generators/ReactGenerator.js, src/generators/ReactGenerator.test.js, src/generators/ReactNativeGenerator.js, src/generators/ReactNativeGenerator.test.js, templates/react-common/actions/foo/create.js, templates/react-common/actions/foo/delete.js, templates/react-common/actions/foo/list.js, templates/react-common/actions/foo/show.js, templates/react-common/actions/foo/update.js, templates/react-common/utils/fetch.js
* Generate only one `fetch` file per project and move it under the `utils/` directory
* Move `_entrypoint.js` in `config/` (as done in the VueJS generator)
=> [react] Refactor fetch generation

src/generators/BaseGenerator.js, templates/_entrypoint.js
If the URL contains a port, it was duplicated in `_entrypoint.js` because `host` already contains the port (`hostname` doesn't).
This PR fixes this bug.
=> Fix entrypoint generation

templates/react-common/actions/foo/list.js, templates/react-common/reducers/foo/list.js, templates/react/components/foo/List.js, templates/react/routes/foo.js, templates/react/utils/helpers.js
* Rely on React Router (the URL change when going to another page)
* Use the Bootstrap `pagination` component
* Clean the code (the `list`, `page` and `view` reducers have been merged)
* Fix the following error `Given action "GREETING_LIST_VIEW", reducer "view" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.` (it was a bug in the `view` reducer, that has been removed in this PR)
* Don't crash when filters are added
* Support new paginators (partial, …
=> Improve the pagination system

templates/react/components/foo/Create.js, templates/react/components/foo/Form.js, templates/react/components/foo/List.js, templates/react/components/foo/Show.js, templates/react/components/foo/Update.js
=> bootstrap 4 buttons

.eslintrc.js, .travis.yml, package.json, src/generators.js, src/generators/AdminOnRestGenerator.js, src/generators/AdminOnRestGenerator.test.js, src/generators/BaseGenerator.js, src/generators/ReactGenerator.js, src/generators/ReactGenerator.test.js, src/generators/ReactNativeGenerator.js, src/generators/ReactNativeGenerator.test.js, src/generators/TypescriptInterfaceGenerator.js, src/generators/TypescriptInterfaceGenerator.test.js, src/generators/VueGenerator.js, src/generators/VueGenerator.test.js, src/index.js, yarn.lock
=> Configure Prettier. Adapt the Travis setup.

README.md, package.json, src/index.js, yarn.lock
The work still in progress, but I'm open this Pull Request just to let you guys know how it is going.
I'm open a PR to [api-doc-parser](https://github.com/api-platform/api-doc-parser/pull/30) as well, including this feature.
=> Add option to use swagger documentation as resource type

package.json, templates/react/components/foo/Form.js
This patch fixes a bug occuring when sending empty relations: the JSON was containing `[""]` instead of `[]`.
=> Allow to send empty relation lists

src/generators/BaseGenerator.js, templates/react/components/foo/Form.js
Currently, numbers are not normalized. Consequently they are sent as strings to the API, and rejected. This patch corrects this behavior.
=> Fix numbers normalization

CONTRIBUTING.md
| Fixed tickets | _none_
| Doc PR        | _none_
Fixing the contribution guide to match the project.
=> Fix the contribution guide

templates/vue/utils/fetch.js
| Fixed tickets | _none_
| Doc PR        | _none_
When you create an app with your API endpoints on a subpath, for instance, `http://yoursite.tld/api`, the `/api` part of the URL was lost because of a behaviour of the JS `URL` prototype.
This PR solves that. Basically, it checks if the ENTRYPOINT has a trailing slash. If it doesn’t, the trailing slash is added, so the path is well appended to the URL.
Plus, we now use the `URL.href` property instead of the `toString()` function.
=> Fix the entrypoint missing the path prefix

src/generators/TypescriptInterfaceGenerator.js, src/generators/TypescriptInterfaceGenerator.test.js, templates/typescript/interface.ts
| Fixed tickets |
I've noticed that the generated interfaces for typescript are missing the `import { ResourceName } from "./resourcefile";` statements, making them less useful when used in a Typescript application (imports would need to be manually added everytime).
This PR fixes this and also adds a test to the typescript generator, testing for both interfaces with references to other interfaces and interfaces without references.
=> Add imports to typescript generator

src/index.js
Simple PR to add the typescript generator to the list of the available generators in the CLI help string.
=> Add typescript to the generator interface list

src/generators/TypescriptInterfaceGenerator.test.js, templates/typescript/interface.ts
| Bug fix?      | yes (i guess)
| Fixed tickets |
As dicussed in https://github.com/api-platform/client-generator/pull/116
By making the id field non required the interface can be used also for POST operations etc
=> Make id field optional in typescript interface

README.md
| Fixed tickets | /
| Doc PR        | /
ATM, README file recommends to install the module globally (which doesn't work anyway) and the online doc recommends to use `npx` instead. IMHO, the second one should be the only recommandation.
=> fix: README and online doc should be harmonized about module usage

src/generators/TypescriptInterfaceGenerator.js, src/generators/TypescriptInterfaceGenerator.test.js, templates/typescript/interface.ts
If any of our resources are identified using Doctrine's Identity Through Foreign Entities (https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/composite-primary-keys.html#identity-through-foreign-entities) and they also declare a getter function to serialize their id in the id property of the response, then the standard template defined for the typescript interface does not work for them since it creates 2 members named `id` in the interface. This PR fixes it by removing `id` as a hard-coded field in the Handlebars template and by appending the id field to the …
=> Typescript generator: Handle resources with explicit id field

package.json, src/generators.js, src/generators/BaseGenerator.js, src/generators/NextGenerator.js, src/generators/NextGenerator.test.js, src/generators/TypescriptInterfaceGenerator.js, src/index.js, templates/next/components/common/ReferenceLinks.tsx, templates/next/components/foo/List.tsx, templates/next/components/foo/ListItem.tsx, templates/next/components/foo/Show.tsx, templates/next/error/SubmissionError.ts, templates/next/interfaces/Collection.ts, templates/next/interfaces/foo.ts, templates/next/pages/foo.tsx, templates/next/pages/foos.tsx, templates/next/utils/dataAccess.ts, yarn.lock
| Fixed tickets | #109 
| Doc PR        | api-platform/docs#822
=> feat: add next.js generator

.eslintrc.js, src/index.js
| Doc PR        | None (at the moment)
Hi all, today I ran across the need for generating code from an endpoint protected with HTTP Basic Auth. Thus, I've modified the main index.js to allow specifing Basic auth credentials from the command line. Unfortunately, I saw that only the hydra parser accepted an `options` parameter, so I was able to add it there only. 
In order to allow the `new Headers()` call, I also had to edit ESLint settings to allow for the browser env. I'm not sure if this is ok for you or not, so let me know if there's another way to do it.
If this is the way to go, I think I might be …
=> Allow to specify http Basic auth credentials for hydra endpoint

package.json
`pre-commit` turns out to be pretty useful while in the Dev workflow.
Added the following dev-dependencies.
- husky
- lint-staged
=> feat(chore): configure pre-commit hook

templates/vue-common/mixins/ListMixin.js
When sorting or changing a page using Vuetify, the list is not updated. Calling this.resetList fixes the problem.
=> Add reset list

templates/vue/components/foo/Update.vue
| Tickets       | fixes #214 
This PR fix updating a resource in the vue generator. The payload was not sent to the API an throw a 400 http error code.
=> Fix updating a resource in Update.vue

src/generators/TypescriptInterfaceGenerator.js, src/generators/TypescriptInterfaceGenerator.test.js
| Bug fix?      | yes/no
| BC breaks?    | yes (as far as "generators" go)
| Tickets       | none
| Doc PR        | not needed
Hi!
With typescript interfaces, an `id` property is *always* output, even if the API has no id field. Is this on purpose? It was added originally when the typescript interfaces were added (then modified  in #132). Is there a reason `id` should always be included?
Cheers!
=> Don't always output id in typescript interface

README.md, package.json, src/generators/NextGenerator.js, src/index.js, templates/next/components/common/ReferenceLinks.tsx, templates/next/components/foo/Form.tsx, templates/next/components/foo/List.tsx, templates/next/components/foo/Show.tsx, templates/next/pages/foos/[id]/edit.tsx, templates/next/pages/foos/[id]/index.tsx, templates/next/utils/dataAccess.ts
| Bug fix?      | yes 
| New feature?  | yes 
| Tickets       | closes #264, partial fix for #261
=> fix: bugs in the Next generator

templates/next/components/foo/Form.tsx, templates/next/components/foo/List.tsx, templates/next/components/foo/Show.tsx
Added title meta tag in head for SEO.
=> added title meta tag

templates/next/components/foo/Form.tsx, templates/next/components/foo/List.tsx, templates/next/components/foo/Show.tsx
fixed handlebars and JSX syntax errors
=> fixed syntax errors

.github/workflows/release.yml
| Tickets       | Fix #275
Switch to Yarn (the current script call to build is faulty, it should be `npm run build`). Using Yarn allows leveraging `yarn.lock`.
=> ci: use Yarn instead of NPM

templates/next/components/foo/Form.tsx, templates/next/components/foo/List.tsx, templates/next/components/foo/Show.tsx, templates/next/pages/foos/[id]/edit.tsx, templates/next/pages/foos/[id]/index.tsx, templates/next/pages/foos/create.tsx, templates/next/pages/foos/index.tsx
related to #260 
moved title meta tag in pages instead of components
=> refacto: moved title meta tag in pages

templates/vue/utils/fetch.js, templates/vue/utils/hydra.js
This is a plain copy from the vue-common template.
| Bug fix?      | yes 
| Tickets       | Fix #280 
=> Respect fetch params in Vue template

templates/next/components/common/Pagination.tsx, templates/next/pages/foos/[id]/edit.tsx, templates/next/pages/foos/[id]/index.tsx, templates/next/pages/foos/create.tsx, templates/next/pages/foos/index.tsx, templates/next/utils/dataAccess.ts, templates/next/utils/mercure.ts
| Tickets       | #289 #288
| Doc PR        | N/A
=> fix: update next template with getStaticPaths

templates/react-common/utils/dataAccess.js
| Doc PR        | api-platform/docs
When using normalization groups to expose some properties of a nested object, the current code only retrieves the IRI. It seems interesting to be able to normalize the nested item if it is an object, and return the real object instead of a string IRI.
=> feat: Normalize nested objects

package.json, src/generators.js, src/index.js
| Tickets       | #54
| Doc PR        | api-platform/docs#1469
This allow the `-g`/`--generator` argument to specify a path, allowing to use custom generators.
The argument can point to any node module.
A quick and dirty command to test is available as `yarn test-gen-custom`.
Notes: 
- the **lib entrypoint is now an `async` function** because we do a _dynamic import_ to load the custom generator inside `src/generators.js`
TODO:
=> feat: new argument to use a custom external generator

src/index.js
In attempting to fix an empty `options` object overshadowing the options set by the user via CLI, #316 mistakenly adjusted `options.username`, `options.password` and `options.bearer` to be attributes of the newly introduced `parserOptions`. They should, however, still refer to the `options` object that holds all the information previously set via CLI arguments.
I also added two comments to make the difference between the two sets of options more clear.
| Branch?       | current stable version branch for bug fixes 
| Tickets       | n.a. 
| Doc PR        | n.a.
=> fix: don't ignore login data set via CLI params (regression from #316)

package.json, src/generators/TypescriptInterfaceGenerator.js, src/generators/TypescriptInterfaceGenerator.test.js, templates/typescript/interface.ts, yarn.lock
With the following entity:
```yaml
resources:
App\Entity\FooBar:
shortName: foo-bar
```
typescript template outputs invalid JS:
```ts
type foo-bar {
// ...
}
```
The following PR replaces dashes to underscores to produce valid JS code.
=> fix js identifiers containing dashes

templates/next/components/common/Pagination.tsx, templates/next/components/common/ReferenceLinks.tsx, templates/next/components/foo/Form.tsx, templates/next/components/foo/List.tsx, templates/next/components/foo/Show.tsx, tests/create.spec.ts, tests/edit.spec.ts, tests/show.spec.ts
! Needs to be merged at the same time as [#2320](https://github.com/api-platform/api-platform/pull/2320)
=> feat: update Next.js generator style with tailwind

templates/react/components/foo/Show.tsx
While I was testing client-create for React I found an hardcoded value in the template
My entity has the name "MyValue" but showing "MyValueretrieved" as shown in the below screenshot
After testing with `testgen.sh`, the result is :
=> fix: remove hardcoded value in react 'Show' template

src/generators/ReactGenerator.js, templates/nuxt/components/foo/FooList.vue, templates/nuxt/composables/api.ts, templates/react-common/actions/foo/list.js, templates/react-common/reducers/foo/list.js, templates/react-common/utils/dataAccess.js, templates/react-native/components/foo/List.js, templates/react-native/utils/helpers.js, templates/react/components/Pagination.tsx, templates/react/components/foo/List.tsx, templates/react/hooks/fetch.ts, templates/react/hooks/mercure.ts, templates/react/hooks/show.ts, templates/react/interfaces/Collection.ts, templates/vuetify/store/foo/list.ts
Change hardcoded values of hydra prefix in templates.
=> fix(hydra) : change hardcoded hydra prefix in templates

src/generators/BaseGenerator.js
| Tickets       | None
| Doc PR        | Not needed
HTML input type "dateTime" seems not complient with official specifications ? 
I suggest to use "datetime-local" instead.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
https://www.w3schools.com/tags/att_input_type_datetime-local.asp
=> Bugfix : input dateTime type to be complient with html specifications
